---
abstract: 'converts Perl XS code into C code'
author:
  - 'Ken Williams, <ken@mathforum.org>'
  - 'David Golden, <dagolden@cpan.org>'
build_requires:
  Carp: 0
  DynaLoader: 0
  ExtUtils::CBuilder: 0
  Test::More: 0.47
generated_by: 'Module::Build version 0.3603'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: ExtUtils-ParseXS
provides:
  ExtUtils::ParseXS:
    file: lib/ExtUtils/ParseXS.pm
    version: 2.2201
requires:
  Cwd: 0
  Exporter: 0
  File::Basename: 0
  File::Spec: 0
  Symbol: 0
resources:
  MailingList: mailto:perl5-porters@perl.org
  bugtracker: http://rt.cpan.org/Dist/Display.html?Queue=ExtUtils-ParseXS
  license: http://dev.perl.org/licenses/
  repository: git://github.com/dagolden/extutils-parsexs.git
version: 2.2201
